[package]
name = 'rambutan'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.88'

[lib]
crate-type = [ 'rlib', 'staticlib' ]
name = 'rambutan'

[[bin]]
name = 'document'
path = 'document.rs'

[dependencies]
extendr-api = '*'
futures = "0.3.32"
http = "1.4.2"
lychee-lib = "0.24.2"
regex = "1.12.4"
reqwest = "0.13.4"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.38.2", features = ["rt-multi-thread"] }
toml = "1.1.2"

[profile.release]
lto = true
codegen-units = 1
