# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rambutan, .registration = TRUE
NULL

#' Check a single URL with lychee and return its status.
#' @noRd
check_url_impl <- function(url, exclude, include, timeout, max_redirects, max_retries, retry_wait_time, user_agent, method, accept, exclude_all_private, exclude_private, exclude_link_local, exclude_loopback, require_https, include_mail, header_names, header_values) .Call(wrap__check_url_impl, url, exclude, include, timeout, max_redirects, max_retries, retry_wait_time, user_agent, method, accept, exclude_all_private, exclude_private, exclude_link_local, exclude_loopback, require_https, include_mail, header_names, header_values)

#' Check multiple URLs concurrently with lychee.
#' @noRd
check_urls_impl <- function(urls, exclude, include, timeout, max_redirects, max_retries, retry_wait_time, user_agent, method, accept, exclude_all_private, exclude_private, exclude_link_local, exclude_loopback, require_https, include_mail, header_names, header_values) .Call(wrap__check_urls_impl, urls, exclude, include, timeout, max_redirects, max_retries, retry_wait_time, user_agent, method, accept, exclude_all_private, exclude_private, exclude_link_local, exclude_loopback, require_https, include_mail, header_names, header_values)

#' Scan files, directories, or glob patterns for links and check each one.
#' @noRd
check_paths_impl <- function(paths, exclude, include, timeout, max_redirects, max_retries, retry_wait_time, user_agent, method, accept, exclude_all_private, exclude_private, exclude_link_local, exclude_loopback, require_https, include_mail, header_names, header_values) .Call(wrap__check_paths_impl, paths, exclude, include, timeout, max_redirects, max_retries, retry_wait_time, user_agent, method, accept, exclude_all_private, exclude_private, exclude_link_local, exclude_loopback, require_https, include_mail, header_names, header_values)

# nolint end
