# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rambutan, .registration = TRUE
NULL

#' Check a single URL with lychee and return its status.
#' @param url A single URL string to check.
#' @return A list with `url`, `is_success`, `code`, and `details`.
#' @export
check_url <- function(url) .Call(wrap__check_url, url)

# nolint end
